apiVersion: v1
kind: PersistentVolume
metadata:
  name: ha-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /ha-config
    server: nfs.blunders.me