{
 "title": "Air Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Location",
    "label": "Location",
    "query": {
     "query": "label_values(airgradient_info,location)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Single Location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(airgradient_temperature_celsius{location=\"$Location\"} * 1.8) + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_humidity_percent{location=\"$Location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2 Levels",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_co2_ppm{location=\"$Location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TVOC Index",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_tvoc_index{location=\"$Location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NOx Index",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_nox_index{location=\"$Location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PM2.5",
   "type": "stat",
   "description": "Micrograms per cubic meter",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_pm2d5_ugm3{location=\"$Location\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PM10",
   "type": "stat",
   "description": "Micrograms per cubic meter",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_pm10_ugm3{location=\"$Location\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PM1",
   "type": "stat",
   "description": "Micrograms per cubic meter",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_pm1_ugm3{location=\"$Location\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "PM0.3",
   "type": "stat",
   "description": "picograms per 100ml",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_pm0d3_p100ml{location=\"$Location\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "All Locations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Temperature in Fahrenheit",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(airgradient_temperature_celsius * 1.8) + 32",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Relative Humidity Percentage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "airgradient_humidity_percent", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "CO2 PPM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "targets": [
    { "expr": "airgradient_co2_ppm", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "TVOC Index",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "targets": [
    { "expr": "airgradient_tvoc_index", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "NOx Index",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 42 },
   "targets": [
    { "expr": "airgradient_nox_index", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "PM2.5",
   "type": "timeseries",
   "description": "micrograms per cubic meter",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "expr": "airgradient_pm2d5_ugm3", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "PM1",
   "type": "timeseries",
   "description": "micrograms per cubic meter",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 54 },
   "targets": [
    { "expr": "airgradient_pm1_ugm3", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "PM10",
   "type": "timeseries",
   "description": "micrograms per cubic meter",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 54 },
   "targets": [
    { "expr": "airgradient_pm10_ugm3", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "PM0.3",
   "type": "timeseries",
   "description": "picograms per 100ml",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 66 },
   "targets": [
    { "expr": "airgradient_pm0d3_p100ml", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "Compare In Location",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temp, CO2, Humidity %",
     "type": "timeseries",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "airgradient_co2_ppm{location=\"$Location\"}",
       "legendFormat": "CO2 PPM"
      },
      {
       "expr": "(airgradient_temperature_celsius{location=\"$Location\"} * 1.8) + 32",
       "legendFormat": "Temperature in F"
      },
      {
       "expr": "airgradient_humidity_percent{location=\"$Location\"}",
       "legendFormat": "Humidity %"
      }
     ]
    },
    {
     "title": "pm2.5, pm10, pm1",
     "type": "timeseries",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "expr": "airgradient_pm2d5_ugm3{location=\"$Location\"}",
       "legendFormat": "pm2.5"
      },
      {
       "expr": "airgradient_pm10_ugm3{location=\"$Location\"}",
       "legendFormat": "pm10"
      },
      {
       "expr": "airgradient_pm1_ugm3{location=\"$Location\"}",
       "legendFormat": "pm1"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true
  }
 ]
}