{
 "title": "Resources by Node",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "machine_memory_bytes{node=\"$Node\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "CPU Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(machine_cpu_cores{node=\"$Node\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ram limits",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{node=\"$Node\", resource=\"memory\", cluster=\"$cluster\"} / 1000000",
     "legendFormat": "{{container}}({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{node=\"$Node\", resource=\"cpu\", cluster=\"$cluster\"}",
     "legendFormat": "{{container}}({{pod}})"
    }
   ]
  },
  {
   "title": "Ram requests",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{node=\"$Node\", resource=\"memory\", cluster=\"$cluster\"} / 1000000",
     "legendFormat": "{{container}}({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{node=\"$Node\", resource=\"cpu\", cluster=\"$cluster\"}",
     "legendFormat": "{{container}}({{pod}})"
    }
   ]
  }
 ]
}