apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
- name: victoria-logs-collector
  releaseName: vl-collector
  namespace: monitoring
  repo: https://victoriametrics.github.io/helm-charts/
  version: "0.2.14"
  valuesInline:
    remoteWrite:
      - url: http://victoria-logs-victoria-logs-single-server:9428
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    tolerations:
      - effect: NoSchedule
        operator: Exists
