apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika-deployment
  labels:
    app: paperless-tika
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-tika
  template:
    metadata:
      labels:
        app: paperless-tika
    spec:
      containers:
      - name: tika
        image: tika-container-image
        securityContext:
          privileged: false
          runAsUser: 35002
          runAsGroup: 35002
        env:
        - name: TZ
          value: "America/Denver"
        ports:
        - containerPort: 9998
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "500m"