apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless

resources:
- deployment.yaml
- service.yaml

images:
  - name: tika-container-image
    newName: docker.io/apache/tika
    newTag: "3.2.3.0-full"