apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-user-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-prod
  target: 
    name: grafana-admin-user-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        admin-user: '{{ .user }}'
        admin-password: '{{ .password }}'
  data:
  - secretKey: user
    remoteRef:
      key: grafana-admin-user
      property: user
  - secretKey: password
    remoteRef:
      key: grafana-admin-user
      property: password
    