apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless

resources:
- deployment.yaml
- service.yaml

images:
  - name: gotenberg-container-image
    newName: gotenberg/gotenberg
    newTag: "8.14.1"