apiVersion: v1
kind: PersistentVolume
metadata:
  name: abs-config-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /abs-config
    server: nfs.blunders.me