apiVersion: v1
kind: PersistentVolume
metadata:
  name: abs-media-pv
spec:
  capacity:
    storage: 500Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /abs
    server: nfs.blunders.me