apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-applicationsets
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  source:
    repoURL: "https://github.com/unknownblunders/K8s.git"
    path: manifests/apps/argo-appsets
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true