apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gatus
  source:
    repoURL: "https://github.com/unknownblunders/K8s.git"
    path: manifests/apps/gatus
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
