apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-apps
spec:
  generators:
  - list:
      elements:
      - appName: jellyfin
        namespace: jellyfin
      - appName: audiobookshelf
        namespace: abs
      - appName: minecraft
        namespace: minecraft
      - appName: home-assistant
        namespace: ha
      - appName: immich
        namespace: immich
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/unknownblunders/K8s.git
        targetRevision: main
        path: manifests/apps/{{appName}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true