apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless

generators:
- ksops-secrets-gen.yaml

resources:
- pv.yaml
- pvc.yaml
- deployment.yaml
- service.yaml

images:
  - name: paperless-pg-container-image
    newName: docker.io/library/postgres
    newTag: "16.6"