apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless

resources:
- pg-secrets-es.yaml
- pv.yaml
- pvc.yaml
- deployment.yaml
- service.yaml

images:
  - name: paperless-pg-container-image
    newName: docker.io/library/postgres
    newTag: "16.8"