apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pg-pvc
spec:
  storageClassName: nfs
  volumeName: paperless-pg-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi