apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
- deployment.yaml
- service.yaml
- pg-secrets-es.yaml

images:
  - name: immich-pg-container-image
    newName: tensorchord/pgvecto-rs
    newTag: "pg14-v0.2.0"