apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

resources:
- deployment.yaml
- service.yaml
- pg-secrets-es.yaml

images:
  - name: immich-pg-container-image
    newName: ghcr.io/immich-app/postgres
    newTag: "14-vectorchord0.3.0-pgvectors0.2.0"