apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-pg-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-prod
  target: 
    name: immich-pg-secret
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        POSTGRES_DB: '{{ .db }}'
        POSTGRES_USER: '{{ .username }}'
        POSTGRESS_PASSWORD: '{{ .password }}'
  data:
  - secretKey: db
    remoteRef:
      key: immich-pg-db
      property: database
  - secretKey: username
    remoteRef:
      key: immich-pg-db
      property: username
  - secretKey: password
    remoteRef:
      key: immich-pg-db
      property: password