apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: satisfactory
  name: satisfactory
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.7.4
  name: satisfactory-service
  namespace: satisfactory
spec:
  ports:
  - name: api
    port: 7777
    protocol: TCP
    targetPort: 7777
  - name: game
    port: 7777
    protocol: UDP
    targetPort: 7777
  selector:
    app: satisfactory
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    pv-name: satisfactory
  name: satisfactory-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  mountOptions:
  - hard
  - nfsvers=4.2
  nfs:
    path: /satisfactory
    server: nfs.blunders.me
  storageClassName: nfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-pvc
  namespace: satisfactory
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      pv-name: satisfactory
  storageClassName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: satisfactory
  name: satisfactory-deployment
  namespace: satisfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      containers:
      - env:
        - name: PGID
          value: "1014"
        - name: PUID
          value: "1014"
        - name: ROOTLESS
          value: "true"
        - name: MAXPLAYERS
          value: "8"
        image: ghcr.io/unknownblunders/satisfactory:e7b4acb84cb0ad1e018cd7b5662b6291606044c3
        name: satisfactory
        ports:
        - containerPort: 7777
          name: api
          protocol: TCP
        - containerPort: 7777
          name: game
          protocol: UDP
        resources:
          limits:
            cpu: 2000m
            memory: 8000Mi
          requests:
            cpu: 100m
            memory: 4000Mi
        securityContext:
          runAsGroup: 1014
          runAsUser: 1014
        volumeMounts:
        - mountPath: /config
          name: satisfactory-pvc
      volumes:
      - name: satisfactory-pvc
        persistentVolumeClaim:
          claimName: satisfactory-pvc
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: satisfactory
  name: satisfactory
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.7.4
  name: satisfactory-service
  namespace: satisfactory
spec:
  ports:
  - name: api
    port: 7777
    protocol: TCP
    targetPort: 7777
  - name: game
    port: 7777
    protocol: UDP
    targetPort: 7777
  selector:
    app: satisfactory
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    pv-name: satisfactory
  name: satisfactory-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  mountOptions:
  - hard
  - nfsvers=4.2
  nfs:
    path: /satisfactory
    server: nfs.blunders.me
  storageClassName: nfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: satisfactory-pvc
  namespace: satisfactory
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      pv-name: satisfactory
  storageClassName: nfs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: satisfactory
  name: satisfactory-deployment
  namespace: satisfactory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: satisfactory
  template:
    metadata:
      labels:
        app: satisfactory
    spec:
      containers:
      - env:
        - name: PGID
          value: "1014"
        - name: PUID
          value: "1014"
        - name: ROOTLESS
          value: "true"
        - name: MAXPLAYERS
          value: "8"
        image: ghcr.io/unknownblunders/satisfactory:e7b4acb84cb0ad1e018cd7b5662b6291606044c3
        name: satisfactory
        ports:
        - containerPort: 7777
          name: api
          protocol: TCP
        - containerPort: 7777
          name: game
          protocol: UDP
        resources:
          limits:
            cpu: 2000m
            memory: 8000Mi
          requests:
            cpu: 100m
            memory: 4000Mi
        securityContext:
          runAsGroup: 1014
          runAsUser: 1014
        volumeMounts:
        - mountPath: /config
          name: satisfactory-pvc
      volumes:
      - name: satisfactory-pvc
        persistentVolumeClaim:
          claimName: satisfactory-pvc
