apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: smartctl-exporter
  labels:
    app: smartctl-exporter
spec:
  selector:
    matchLabels:
      app: smartctl-exporter
  template:
    metadata:
      labels:
        app: smartctl-exporter
    spec:
      tolerations:
      # this tolerations are to have the daemonset runnable on control plane nodes
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: smartctl-exporter
        image: smartctl-exporter-image
        securityContext:
          privileged: true
          runAsUser: 0
        ports:
        - name: http-metrics
          containerPort: 9633
        resources:
          limits:
            memory: 64Mi
            cpu: 500m
        volumeMounts:
        - name: dev
          readOnly: true
          mountPath: /dev
      volumes:
      - name: dev
        hostPath:
          path: /dev