apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
- daemonset.yaml
- service.yaml
- vmscrape.yaml

images:
  - name: smartctl-exporter-image
    newName: quay.io/prometheuscommunity/smartctl-exporter
    newTag: v0.12.0
