apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  labels:
    app.kubernetes.io/name: prometheus-smartctl-exporter
  name: smartctl-exporter-scrpae
  namespace: monitoring
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus-smartctl-exporter 