apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich

helmCharts:
- name: immich
  releaseName: immich
  namespace: immich
  repo: https://immich-app.github.io/immich-charts
  version: "0.9.0"
  valuesFile: values.yaml

resources:
- ns.yaml
- storage
- postgres