# -- If this chart is used in "Argocd" with "releaseName" field then
# VMServiceScrapes couldn't select the proper services.
# For correct working need set value 'argocdReleaseOverride=$ARGOCD_APP_NAME'
argocdReleaseOverride: ""
serviceAccount:
  create: true
victoria-metrics-operator:
  enabled: true
  serviceMonitor:
    enabled: true
  crd:
    create: true
# Configures vmsingle params
vmsingle:
  enabled: true
  # -- Full spec for VMSingle CRD. Allowed values describe [here](https://docs.victoriametrics.com/operator/api#vmsinglespec)
  spec:
    port: "8428"
    # -- Data retention period. Possible units character: h(ours), d(ays), w(eeks), y(ears), if no unit character specified - month. The minimum retention period is 24h. See these [docs](https://docs.victoriametrics.com/single-server-victoriametrics/#retention)
    retentionPeriod: "6"
    replicaCount: 1
    extraArgs:
      maxLabelsPerTimeseries: "120"
    resources:
      limits:
        memory: 4000Mi
      requests:
        memory: 4000Mi
        cpu: 2
    securityContext:
      runAsUser: 1015
      runAsGroup: 1015
    storage:
      storageClassName: nfs
      volumeName: metrics-pv
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
  ingress:
    enabled: false
  route:
    enabled: true
    hostnames:
      - metrics.blunders.me
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: envoy-internal
        namespace: envoy-gateway
        sectionName: https
vmalert:
  enabled: true
  spec:
    extraArgs:
      external.url: https://metrics.blunders.me
  ingress:
    enabled: false
alertmanager:
  enabled: true
  route:
    enabled: true
    hostnames:
      - alerts.blunders.me
    parentRefs:
      - group: gateway.networking.k8s.io
        kind: Gateway
        name: envoy-internal
        namespace: envoy-gateway
        sectionName: https
  spec:
    externalURL: https://alerts.blunders.me
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ceph-block
          resources:
            requests:
              storage: 1Gi
  useManagedConfig: true
  config:
    route:
      receiver: pushover
      repeat_interval: 12h
      routes:
        - receiver: blackhole
          matchers:
            - alertname = "InfoInhibitor"
        - receiver: blackhole
          matchers:
            - alertname = "Watchdog"
        - receiver: blackhole
          matchers:
            - severity = "info"
      group_by:
        - alertname
        - cluster
        - job
      group_interval: 5m
      group_wait: 1m
    inhibit_rules:
      - equal:
          - alertname
          - namespace
        source_matchers:
          - severity = "critical"
        target_matchers:
          - severity = "warning"
    receivers:
      - name: blackhole
      - name: pushover
        pushover_configs:
          - html: true
            message: |-
              {{- range .Alerts }}
                {{- if ne .Annotations.description "" }}
                  {{ .Annotations.description }}
                {{- else if ne .Annotations.summary "" }}
                  {{ .Annotations.summary }}
                {{- else if ne .Annotations.message "" }}
                  {{ .Annotations.message }}
                {{- else }}
                  Alert description not available
                {{- end }}
                {{- if gt (len .Labels.SortedPairs) 0 }}
                  <small>
                    {{- range .Labels.SortedPairs }}
                      <b>{{ .Name }}:</b> {{ .Value }}
                    {{- end }}
                  </small>
                {{- end }}
              {{- end }}
            priority: |-
              {{ if eq .Status "firing" }}1{{ else }}0{{ end }}
            send_resolved: true
            sound: gamelan
            title: >-
              [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
            token:
              name: alertmanager-secret
              key: ALERTMANAGER_PUSHOVER_TOKEN
            url_title: View in Alertmanager
            user_key:
              name: alertmanager-secret
              key: PUSHOVER_USER_KEY
vmagent:
  # -- Create VMAgent CR
  enabled: true
  ingress:
    enabled: false
# I setup grafana operator
defaultDashboards:
  grafanaOperator:
    enabled: true
    spec:
      allowCrossNamespaceImport: true
defaultDatasources:
  grafanaOperator:
    enabled: true
    spec:
      allowCrossNamespaceImport: true
grafana:
  enabled: false
  forceDeployDatasource: true
# -- prometheus-node-exporter dependency chart configuration. For possible values check [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml)
prometheus-node-exporter:
  enabled: true
# -- kube-state-metrics dependency chart configuration. For possible values check [here](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml)
kube-state-metrics:
  enabled: true
# -- Component scraping the kubelets
kubelet:
  enabled: true
  vmScrapes:
    # -- Enable scraping /metrics/cadvisor from kubelet's service
    cadvisor:
      enabled: true
    # -- Enable scraping /metrics/probes from kubelet's service
    probes:
      enabled: true
# Component scraping the kube api server
kubeApiServer:
  # -- Enable Kube Api Server metrics scraping
  enabled: true
# Component scraping the kube controller manager
kubeControllerManager:
  enabled: true
  service:
    selector:
      component: kube-apiserver
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            insecureSkipVerify: true
# Component scraping coreDns. Use either this or kubeDns
coreDns:
  # -- Enabled CoreDNS metrics scraping
  enabled: true
  service:
    enabled: false
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: metrics
      jobLabel: jobLabel
      namespaceSelector:
        matchNames:
          - kube-system
      selector:
        matchLabels:
          k8s-app: kube-dns
          kubernetes.io/name: CoreDNS
# Component scraping etcd
kubeEtcd:
  # -- Enabled KubeETCD metrics scraping
  # I manually created a service scrape for this in ../misc
  enabled: false
# Component scraping kube scheduler
kubeScheduler:
  # -- Enable KubeScheduler metrics scraping
  enabled: true
  vmScrape:
    spec:
      endpoints:
        - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          port: http-metrics
          scheme: https
          tlsConfig:
            insecureSkipVerify: true
additionalVictoriaMetricsMap:
  dockerhub-rules:
    create: true
    groups:
      - name: dockerhub
        rules:
          - alert: DockerhubRateLimitRisk
            annotations:
              summary: There are {{ $value }} containers pulling from Dockerhub. This may lead to rate limiting.
            expr: count(time() - container_last_seen{image=~"(docker.io).*",container!=""} < 30) > 100
            labels:
              severity: critical
  oom-rules:
    create: true
    groups:
      - name: oom
        rules:
          - alert: OomKilled
            annotations:
              summary: Container {{ $labels.container }} in pod {{ $labels.namespace }}/{{ $labels.pod }} has been OOMKilled {{ $value }} times in the last 10 minutes.
            expr: (kube_pod_container_status_restarts_total - kube_pod_container_status_restarts_total offset 10m >= 1) and ignoring (reason) min_over_time(kube_pod_container_status_last_terminated_reason{reason="OOMKilled"}[10m]) == 1
            labels:
              severity: critical
# Component scraping kube proxy
kubeProxy:
  enabled: false
# --  Install VM operator CRDs
crds:
  enabled: true
# -- Install prometheus operator CRDs
prometheus-operator-crds:
  enabled: true
