apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-secrets-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-prod
  target:
    name: paperless-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      data:
        paperless-secret-key: '{{ .key }}'
  data:
    - secretKey: key
      remoteRef:
        key: paperless-secrets
        property: paperless-secret-key
