apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-server-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /paperless-server
    server: nfs.blunders.me