apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-server-pvc
spec:
  storageClassName: nfs
  volumeName: paperless-server-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi