apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: vikunja
  name: vikunja
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja-pg-service
  namespace: vikunja
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: vikunja-pg
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja-redis-service
  namespace: vikunja
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: vikunja-redis
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja-service
  namespace: vikunja
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3456
  selector:
    app: vikunja
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-pg-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  mountOptions:
  - nfsvers=4.2
  nfs:
    path: /vikunja-pg
    server: nfs.blunders.me
  storageClassName: nfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  mountOptions:
  - nfsvers=4.2
  nfs:
    path: /vikunja
    server: nfs.blunders.me
  storageClassName: nfs
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-pg-pvc
  namespace: vikunja
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs
  volumeName: vikunja-pg-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-pvc
  namespace: vikunja
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs
  volumeName: vikunja-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vikunja
  name: vikunja-deployment
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      containers:
      - env:
        - name: VIKUNJA_DATABASE_DATABASE
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: vikunja-pg-secret
        - name: VIKUNJA_DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: vikunja-pg-secret
        - name: VIKUNJA_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: vikunja-pg-secret
        - name: VIKUNJA_SERVICE_JWTSECRET
          valueFrom:
            secretKeyRef:
              key: JWT
              name: vikunja-jwt-secret
        - name: VIKUNJA_SERVICE_PUBLICURL
          value: https://todo.blunders.me
        - name: VIKUNJA_DATABASE_TYPE
          value: postgres
        - name: VIKUNJA_DATABASE_HOST
          value: vikunja-pg-service
        - name: VIKUNJA_DEFAULTSETTINGS_AVATAR_PROVIDER
          value: initials
        - name: VIKUNJA_REDIS_ENABLED
          value: "1"
        - name: VIKUNJA_REDIS_HOST
          value: vikunja-redis-service:6379
        - name: VIKUNJA_CACHE_ENABLED
          value: "1"
        - name: VIKUNJA_CACHE_TYPE
          value: redis
        - name: VIKUNJA_SERVICE_TIMEZONE
          value: America/Denver
        image: docker.io/vikunja/vikunja:0.24.6
        name: vikunja
        ports:
        - containerPort: 3456
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 500m
            memory: 1000Mi
        securityContext:
          runAsGroup: 1017
          runAsUser: 1017
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: vikunja-pg-pvc
      volumes:
      - name: vikunja-pg-pvc
        persistentVolumeClaim:
          claimName: vikunja-pg-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vikunja-pg
  name: vikunja-pg-deployment
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja-pg
  template:
    metadata:
      labels:
        app: vikunja-pg
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: vikunja-pg-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: vikunja-pg-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: vikunja-pg-secret
        image: docker.io/library/postgres:16.6
        name: vikunja-pg
        ports:
        - containerPort: 5432
        resources:
          limits:
            cpu: 100m
            memory: 500Mi
          requests:
            cpu: 10m
            memory: 100Mi
        securityContext:
          runAsGroup: 1016
          runAsUser: 1016
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: vikunja-pg-pvc
      volumes:
      - name: vikunja-pg-pvc
        persistentVolumeClaim:
          claimName: vikunja-pg-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vikunja-redis
  name: vikunja-redis-deployment
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja-redis
  template:
    metadata:
      labels:
        app: vikunja-redis
    spec:
      containers:
      - image: docker.io/library/redis:7.4.1
        name: vikunja-redis
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 10m
            memory: 30Mi
        securityContext:
          privileged: false
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-jwt-external-secret
  namespace: vikunja
spec:
  data:
  - remoteRef:
      key: vikunja-jwt
      property: password
    secretKey: jwt
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-prod
  target:
    creationPolicy: Owner
    name: vikunja-jwt-secret
    template:
      data:
        JWT: '{{ .jwt }}'
      engineVersion: v2
      type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-pg-external-secret
  namespace: vikunja
spec:
  data:
  - remoteRef:
      key: vikunja-pg-db
      property: database
    secretKey: db
  - remoteRef:
      key: vikunja-pg-db
      property: username
    secretKey: username
  - remoteRef:
      key: vikunja-pg-db
      property: password
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-prod
  target:
    creationPolicy: Owner
    name: vikunja-pg-secret
    template:
      data:
        POSTGRES_DB: '{{ .db }}'
        POSTGRES_PASSWORD: '{{ .password }}'
        POSTGRES_USER: '{{ .username }}'
      engineVersion: v2
      type: Opaque
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: prod-cert-issuer
  name: vikunja
  namespace: vikunja
spec:
  ingressClassName: nginx
  rules:
  - host: todo.blunders.me
    http:
      paths:
      - backend:
          service:
            name: vikunja-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - todo.blunders.me
    secretName: vikunja-secret-tls
