apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-exporter-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-prod
  target:
    name: nut-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        router-rb5009.yaml: |
          username: {{ .router_rb5009_username }}
          password: {{ .router_rb5009_password }}
        10g-crs309.yaml: |
          username: {{ .10g_crs309_username }}
          password: {{ .10g_crs309_password }}
        1g-rack-crs326.yaml: |
          username: {{ .1g_rack_crs326_username }}
          password: {{ .1g_rack_crs326_password }}
  data:
    - secretKey: router_rb5009_username
      remoteRef:
        key: router-rb5009-metrics-user
        property: username
    - secretKey: router_rb5009_password
      remoteRef:
        key: router-rb5009-metrics-user
        property: password
    - secretKey: 10g_crs309_username
      remoteRef:
        key: 10g-crs309-metrics-user
        property: username
    - secretKey: 10g_crs309password
      remoteRef:
        key: 10g-crs309-metrics-user
        property: password
    - secretKey: 1g_rack_crs326_username
      remoteRef:
        key: 1g-rack-crs326-metrics-user
        property: username
    - secretKey: 1g_rack_crs326_password
      remoteRef:
        key: 1g-rack-crs326-metrics-user
        property: password
