apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-exporter-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-prod
  target:
    name: mikrotik-exporter-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        router-rb5009.yaml: |
          username: {{ .router_rb5009_username }}
          password: {{ .router_rb5009_password }}
        crs309-10g.yaml: |
          username: {{ .crs309_10g_username }}
          password: {{ .crs309_10g_password }}
        crs326-1g-rack.yaml: |
          username: {{ .crs326_1g_rack_username }}
          password: {{ .crs326_1g_rack_password }}
  data:
    - secretKey: router_rb5009_username
      remoteRef:
        key: router-rb5009-metrics-user
        property: username
    - secretKey: router_rb5009_password
      remoteRef:
        key: router-rb5009-metrics-user
        property: password
    - secretKey: crs309_10g_username
      remoteRef:
        key: 10g-crs309-metrics-user
        property: username
    - secretKey: crs309_10g_password
      remoteRef:
        key: 10g-crs309-metrics-user
        property: password
    - secretKey: crs326_1g_rack_username
      remoteRef:
        key: 1g-rack-crs326-metrics-user
        property: username
    - secretKey: crs326_1g_rack_password
      remoteRef:
        key: 1g-rack-crs326-metrics-user
        property: password
