apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tuppr
helmCharts:
  - name: tuppr
    releaseName: tuppr
    namespace: tuppr
    repo: oci://ghcr.io/home-operations/charts
    version: "0.3.0"
    includeCRDs: true
    valuesInline:
      monitoring:
        serviceMonitor:
          enabled: true
        prometheusRule:
          enabled: true
        dashboards:
          enabled: true
          grafanaOperator:
            enabled: true
            matchLabels:
              dashboards: grafana
resources:
  - talosupgrade.yaml
  - k8supgrade.yaml
