apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mc-echochamber-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  selector:
    matchLabels:
      pv-name: mc-echochamber