clusterName: prod-cluster

# renovate: datasource=github-releases depName=siderolabs/talos
talosVersion: "v1.10.4"
# renovate: datasource=github-releases depName=siderolabs/kubelet
kubernetesVersion: "v1.33.2"
endpoint: "https://cluster.blunders.me:6443"

cniConfig:
  name: none

additionalApiServerCertSans:
- 192.168.6.10

additionalMachineCertSans:
- 192.168.6.10
- cluster.blunders.me

nodes:
- hostname: kcp01.blunders.me
  disableSearchDomain: true
  ipAddress: 192.168.6.11
  controlPlane: true
  installDiskSelector:
    size: '> 200GB'
  nameservers:
  - 192.168.6.1
  networkInterfaces:
  - interface: enp1s0
    dhcp: false
    addresses:
    - 192.168.6.11/23
    routes:
    - network: 0.0.0.0/0
      gateway: 192.168.6.1
    mtu: 1500
    vip:
      ip: 192.168.6.10
- hostname: kcp02.blunders.me
  disableSearchDomain: true
  ipAddress: 192.168.6.12
  controlPlane: true
  installDiskSelector:
    size: '> 200GB'
  nameservers:
  - 192.168.6.1
  networkInterfaces:
  - interface: enp1s0
    dhcp: false
    addresses:
    - 192.168.6.12/23
    routes:
    - network: 0.0.0.0/0
      gateway: 192.168.6.1
    mtu: 1500
    vip:
      ip: 192.168.6.10
- hostname: kcp03.blunders.me
  disableSearchDomain: true
  ipAddress: 192.168.6.13
  controlPlane: true
  installDiskSelector:
    size: '> 200GB'
  nameservers:
  - 192.168.6.1
  networkInterfaces:
  - interface: enp1s0
    dhcp: false
    addresses:
    - 192.168.6.13/23
    routes:
    - network: 0.0.0.0/0
      gateway: 192.168.6.1
    mtu: 1500
    vip:
      ip: 192.168.6.10
- hostname: kw01.blunders.me
  disableSearchDomain: true
  ipAddress: 192.168.6.14
  controlPlane: false
  installDiskSelector:
    size: '> 200GB'
  nameservers:
  - 192.168.6.1
  networkInterfaces:
  - interface: eno1
    dhcp: false
    addresses:
    - 192.168.6.14/23
    routes:
    - network: 0.0.0.0/0
      gateway: 192.168.6.1
    mtu: 1500
- hostname: kw02.blunders.me
  disableSearchDomain: true
  ipAddress: 192.168.6.15
  controlPlane: false
  installDiskSelector:
    size: '> 200GB'
  nameservers:
  - 192.168.6.1
  networkInterfaces:
  - interface: eno1
    dhcp: false
    addresses:
    - 192.168.6.15/23
    routes:
    - network: 0.0.0.0/0
      gateway: 192.168.6.1
    mtu: 1500
- hostname: kw03.blunders.me
  disableSearchDomain: true
  ipAddress: 192.168.6.16
  controlPlane: false
  installDiskSelector:
    size: '< 500GB'
    type: 'nvme'
  nameservers:
  - 192.168.6.1
  networkInterfaces:
  - interface: enp1s0
    dhcp: false
    addresses:
    - 192.168.6.16/23
    routes:
    - network: 0.0.0.0/0
      gateway: 192.168.6.1
    mtu: 1500
controlPlane:
  machineSpec:
      secureboot: true
  schematic:
    customization:
      extraKernelArgs:
        - -lockdown
        - lockdown=integrity
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/mei
  patches: # See issue for sysctl: https://github.com/siderolabs/talos/issues/8952#issuecomment-2200582804
  - &allPatches |-
    machine:
      features:
        kubePrism:
          enabled: true
          port: 7445
        hostDNS:
          enabled: true
          forwardKubeDNSToHost: true
      sysctls:
        kernel.kexec_load_disabled: "1"
      kubelet:
        extraArgs:
          rotate-server-certificates: "true"
        extraConfig:
          maxPods: 150
        nodeIP:
          validSubnets:
              - 192.168.6.0/24
      network:
        extraHostEntries:
          - ip: 192.168.6.10
            aliases:
              - cluster.blunders.me
      time:
        disabled: false
        servers:
          - time.cloudflare.com
    cluster:
      proxy:
          disabled: true

worker:
  machineSpec:
      secureboot: true
  schematic:
    customization:
      extraKernelArgs:
        - -lockdown
        - lockdown=integrity
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/intel-ucode
          - siderolabs/mei
  patches:
  - *allPatches 
