{
 "title": "Air Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Location",
    "label": "Location",
    "query": {
     "query": "label_values(airgradient_info,location)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Single Location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(airgradient_temperature_celsius{location=\"$Location\"} * 1.8) + 32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_humidity_percent{location=\"$Location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CO2 Levels",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_co2_ppm{location=\"$Location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TVOC Index",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airgradient_tvoc_index{location=\"$Location\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "All Locations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature in Fahrenheit",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(airgradient_temperature_celsius * 1.8) + 32",
     "legendFormat": "{{location}}"
    }
   ]
  },
  {
   "title": "Relative Humidity Percentage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "airgradient_humidity_percent", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "CO2 PPM",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "expr": "airgradient_co2_ppm", "legendFormat": "{{location}}" }
   ]
  },
  {
   "title": "TVOC Index",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 22 },
   "targets": [
    { "expr": "airgradient_tvoc_index", "legendFormat": "{{location}}" }
   ]
  }
 ]
}