{
 "title": "Resources by Node",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ram limits",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{node=\"$Node\", resource=\"memory\"} / 1000000",
     "legendFormat": "{{container}}({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Limits",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{node=\"$Node\", resource=\"cpu\"}",
     "legendFormat": "{{container}}({{pod}})"
    }
   ]
  },
  {
   "title": "Ram requests",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{node=\"$Node\", resource=\"memory\"} / 1000000",
     "legendFormat": "{{container}}({{pod}})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{node=\"$Node\", resource=\"cpu\"}",
     "legendFormat": "{{container}}({{pod}})"
    }
   ]
  }
 ]
}