apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /metrics
    server: nfs.blunders.me