apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-ml-pvc
spec:
  storageClassName: nfs
  volumeName: immich-ml-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi