apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pg-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /immich-pg
    server: nfs.blunders.me