apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pg-pvc
spec:
  storageClassName: nfs
  volumeName: immich-pg-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi