apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft

helmCharts:
- name: mc-router
  releaseName: mc-router
  namespace: minecraft
  repo: https://itzg.github.io/minecraft-server-charts/
  version: "1.2.6"
  valuesFile: values.yaml