services:
  minecraft:
    type: LoadBalancer
    port: 25565
    annotations:
      metallb.universe.tf/loadBalancerIPs: 192.168.7.2
  extraServiceSpec:
    externalTrafficPolicy: Local

image:
  # renovate: datasource=github-releases depName=itzg/mc-router
  tag: "v1.35.0"
  pullPolicy: IfNotPresent