image:
  repository: itzg/minecraft-server
  tag: "2024.4.1"
  pullPolicy: IfNotPresent

resources:
  requests:
    memory: 7500Mi
    cpu: 500m
  limits:
    memory: 7500Mi

# mc-td user
podSecurityContext:
  runAsUser: 1005
  runAsGroup: 1005
  runAsNonRoot: true

persistence:
  storageClass: "-"
  dataDir:
    enabled: true
    existingClaim: mc-td-pvc

minecraftServer:
  eula: "TRUE"
  # may be SNAPSHOT or a specific version number
  version: 1.20.4
  type: "PAPER"
  difficulty: normal
  # allowed players' names comma separated, leave blank to allow any players
  whitelist: Bjs575,RegardedHarmful,murderousMabel
  # comma separated admin players' names
  ops: RegardedHarmful
  # always set game mode when a player connects
  forcegameMode: true
  # size of the world in blocks radius from spawn point (default is 29999984)
  maxWorldSize: 29999984
  # default game mode for players creative,adventure,survival or spectator
  gameMode: survival
  # message in the launcher
  motd: "ThisDick Minecraft Server"
  # player vs player enabled
  pvp: true
  # REQUIRED this means you get nodePort exposed on all nodes and will get
  # directed to the correct node if you connect to any
  serviceType: ClusterIP
  servicePort: 25565
  # how far from the player are chunks rendered on the server
  # 10 is default, larger is nice on high spec hardware
  # I believe 25 is the client max so larger is wasted
  viewDistance: 20
  # memory to allocate to the jvm - if you change this also change the K8s resource request
  memory: 6g
  # By default, the server configuration will be created and set based on the following environment variables, but only the first time the server is started
  # If you would like to override the server configuration each time the container starts up, you can set this to true
  # see https://github.com/itzg/docker-minecraft-server#server-configuration
  overrideServerProperties: false


serviceAnnotations: 
  mc-router.itzg.me/externalServerName: main.kmc.blunders.me,main.mc.blunders.me,mc.thisdick.org,thisdick.org,minecraft.thisdick.org
podLabels: 
  world: mc-td
deploymentLabels: 
  world: mc-td
serviceLabels: 
  world: mc-td
