apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jellyfin

resources:
- ns.yaml
- ./storage
- deployment.yaml
- service.yaml
- ingress.yaml
# - ingress-pub.yaml

images:
  - name: jellyfin-container-image
    newName: ghcr.io/jellyfin/jellyfin
    newTag: 10.9.8
