apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: abs

resources:
- ns.yaml
- ./storage
- deployment.yaml
- service.yaml
- ingress.yaml
- ingress-pub.yaml

images:
  - name: abs-container-image
    newName: ghcr.io/advplyr/audiobookshelf
    newTag: 2.26.2