apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: abs
spec:
  hostnames:
    - bookshelf.blunders.me
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-internal
      namespace: envoy-gateway
      sectionName: https
  rules:
    - backendRefs:
      - kind: Service
        name: abs-service
        port: 80
