apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs
  namespace: monitoring
spec:
  plugins:
    - name: victoriametrics-logs-datasource
      version: 0.26.3
  allowCrossNamespaceImport: true
  datasource:
    access: proxy
    isDefault: false
    name: victorialogs
    type: victoriametrics-logs-datasource
    url: >-
      http://victoria-logs-victoria-logs-single-server.monitoring.svc.cluster.local:9428
  instanceSelector:
    matchLabels:
      dashboards: grafana
