apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
- name: victoria-logs-single
  releaseName: victoria-logs
  namespace: monitoring
  repo: https://victoriametrics.github.io/helm-charts/
  version: "0.11.5"
  valuesFile: values.yaml

resources:
- pv.yaml
- pvc.yaml
- metrics-scrape.yaml