apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: victoria-logs-scrape
spec:
  discoveryRole: service
  endpoints:
  - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-logs-single
