apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pv
  labels:
    pv-name: logs-pv
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /victoria-logs
    server: nfs.blunders.me