apiVersion: v1
kind: PersistentVolume
metadata:
  name: vikunja-pg-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  mountOptions:
    - nfsvers=4.2
  nfs:
    path: /vikunja-pg
    server: nfs.blunders.me