apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: satisfactory

resources:
- ns.yaml
- ./storage
- deployment.yaml
- service.yaml

images:
  - name: satisfactory-container-image
    newName: ghcr.io/unknownblunders/satisfactory
    newTag: "e7b4acb84cb0ad1e018cd7b5662b6291606044c3"
