apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: satisfactory

resources:
- ns.yaml
- ./storage
- deployment.yaml
- service.yaml

images:
  - name: satisfactory-container-image
    newName: docker.io/wolveix/satisfactory-server
    newTag: v1.8.7
